name: Leptosfmt

on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        required: false
        type: string
      name:
        default: Leptopsfmt
        required: false
        type: string
      command:
        default: "--check ."
        required: true
        type: string

jobs:
  check-leptos:
    name: ${{ inputs.name }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install LeptosFmt
        run: cargo install leptosfmt --version 0.1.32
      - name: ${{ inputs.name }}
        run: leptosfmt ${{ inputs.command }}
