name: Quality Gate

on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        required: false
        type: string
      checks-command:
        default: "--all --check"
        required: false
        type: string
      clippy-command:
        default: "-- -D warnings"
        required: false
        type: string
      leptos-command:
        default: "--check ."
        required: false
        type: string

jobs:
  check-format:
    uses: ./.github/workflows/format.yml
    with:
      name: Checks
      runs-on: ${{ inputs.runs-on }}
      command: ${{ inputs.checks-command }}

  check-leptosfmt:
    uses: ./.github/workflows/leptosfmt.yml
    with:
      name: LeptosFmt
      runs-on: ${{ inputs.runs-on }}
      command: ${{ inputs.leptos-command }}

  check-clippy:
    needs: [check-format]
    uses: ./.github/workflows/clippy.yml
    with:
      name: Clippy
      runs-on: ${{ inputs.runs-on }}
      command: ${{ inputs.clippy-command }}
